services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/db-init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-data:
